name: Validation

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Proof HTML
        uses: anishathalye/proof-html@v2
        with:
          directory: ./
          check_css: false
          ignore_url: |
            https://fonts.googleapis.com
            https://fonts.gstatic.com
          ignore_url_re: |
            ^https://www.linkedin.com/
